fix: package-lock added

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -1,7 +1,7 @@
 name: Pull Request
 
 on:
-  pull_request:
+  pull_request_target:
 
 jobs:
   prepare:
@@ -10,7 +10,12 @@ jobs:
     steps:
       - shell: bash
         run: |
-
+          if [[ "${GITHUB_HEAD_REF}" =~ ^(bugfix|hotfix|test|feature)/EDKUI-[0-9]+/[a-zA-Z0-9_-]+$ || "${GITHUB_HEAD_REF}" == "main" ]]; then
+            echo "✅ Branch name is valid."
+          else
+            echo "❌ Invalid branch name: ${GITHUB_HEAD_REF}"
+            exit 1
+          fi
 
   ci:
     needs: prepare
